//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.OutputCache.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.OutputCache.Resource.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding response to cache. Key = &apos;{0}&apos;.
        /// </summary>
        internal static string Adding_response_to_cache {
            get {
                return ResourceManager.GetString("Adding_response_to_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cache item found but callback status is IgnoreThisRequest. Key = &apos;{0}&apos;. Returning from.
        /// </summary>
        internal static string Callback_status_is_IgnoreThisRequest {
            get {
                return ResourceManager.GetString("Callback_status_is_IgnoreThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get snapshot if not buffered..
        /// </summary>
        internal static string Cannot_get_snapshot_if_not_buffered {
            get {
                return ResourceManager.GetString("Cannot_get_snapshot_if_not_buffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use snapshot after headers sent..
        /// </summary>
        internal static string Cannot_use_snapshot_after_headers_sent {
            get {
                return ResourceManager.GetString("Cannot_use_snapshot_after_headers_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cache item found but contains a {0} and no {1} specified. Key=&apos;{2}&apos;. Returning from.
        /// </summary>
        internal static string Contains_querystring_and_no_VaryByParam_specified {
            get {
                return ResourceManager.GetString("Contains_querystring_and_no_VaryByParam_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add non-cacheable post. Key =&apos;{0}&apos;.
        /// </summary>
        internal static string Couldnot_add_non_cacheable_post {
            get {
                return ResourceManager.GetString("Couldnot_add_non_cacheable_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit, conditional request satisfied, status=304. Key=&apos;{0}&apos;. Returning from.
        /// </summary>
        internal static string Hit_conditional_request_satisfied {
            get {
                return ResourceManager.GetString("Hit_conditional_request_satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore If-Modified-Since header, invalid format: &apos;{0}&apos;.
        /// </summary>
        internal static string Ignore_IfModifiedSince_header {
            get {
                return ResourceManager.GetString("Ignore_IfModifiedSince_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid validation status, ignoring it, status = &apos;{0}&apos;. Key = &apos;{1}&apos;.
        /// </summary>
        internal static string Invalid_validation_status {
            get {
                return ResourceManager.GetString("Invalid_validation_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method is not.
        /// </summary>
        internal static string method_is_not {
            get {
                return ResourceManager.GetString("method_is_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cache item found but method is {0} and no {1} specified. Key=&apos;{2}&apos;. Returning from.
        /// </summary>
        internal static string Method_is_POST_and_no_VaryByParam_specified {
            get {
                return ResourceManager.GetString("Method_is_POST_and_no_VaryByParam_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.AspNet.OutputCache Default In-Memory Provider.
        /// </summary>
        internal static string Microsoft_AspNet_OutputCache_Default_InMemory_Provider {
            get {
                return ResourceManager.GetString("Microsoft_AspNet_OutputCache_Default_InMemory_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss, key could not be created for {0} item. Returning from.
        /// </summary>
        internal static string Miss_key_could_not_be_created_for_varyby_item {
            get {
                return ResourceManager.GetString("Miss_key_could_not_be_created_for_varyby_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not returning found item due to Cache-Control: max-age directive. Returning from.
        /// </summary>
        internal static string Not_returning_found_item_due_to_Cache_Control_max_age_directive {
            get {
                return ResourceManager.GetString("Not_returning_found_item_due_to_Cache_Control_max_age_directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not returning found item due to Cache-Control: min-fresh directive. Returning from.
        /// </summary>
        internal static string Not_returning_found_item_due_to_Cache_Control_min_fresh_directive {
            get {
                return ResourceManager.GetString("Not_returning_found_item_due_to_Cache_Control_min_fresh_directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cache item found but callback invalidated it. key= &apos;{0}&apos;. Returning from.
        /// </summary>
        internal static string Output_cache_item_found_but_callback_invalidated_it {
            get {
                return ResourceManager.GetString("Output_cache_item_found_but_callback_invalidated_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputCacheModuleEnter.
        /// </summary>
        internal static string OutputCacheModuleEnter {
            get {
                return ResourceManager.GetString("OutputCacheModuleEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputCache Module Leave.
        /// </summary>
        internal static string OutputCacheModuleLeave {
            get {
                return ResourceManager.GetString("OutputCacheModuleLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider does not support policy for responses..
        /// </summary>
        internal static string Provider_does_not_support_policy_for_responses {
            get {
                return ResourceManager.GetString("Provider_does_not_support_policy_for_responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output cache item found but this is a {0} and {1} is true. Key=&apos;{2}&apos;. Returning from.
        /// </summary>
        internal static string Range_request_and_IgnoreRangeRequests_is_true {
            get {
                return ResourceManager.GetString("Range_request_and_IgnoreRangeRequests_is_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.Flush() inside GetVaryByCustomstring key =&apos;{0}&apos;.
        /// </summary>
        internal static string Response_Flush_inside_GetVaryByCustomstring {
            get {
                return ResourceManager.GetString("Response_Flush_inside_GetVaryByCustomstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning from.
        /// </summary>
        internal static string Returning_from {
            get {
                return ResourceManager.GetString("Returning_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping lookup because of Cache-Control: no-cache or no-store directive. Returning from.
        /// </summary>
        internal static string Skipping_lookup_because_of_Cache_Control_no_cache_or_no_store_directive {
            get {
                return ResourceManager.GetString("Skipping_lookup_because_of_Cache_Control_no_cache_or_no_store_directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping lookup because of Pragma: no-cache directive. Returning from.
        /// </summary>
        internal static string Skipping_lookup_because_of_Pragma_no_cache_directive {
            get {
                return ResourceManager.GetString("Skipping_lookup_because_of_Pragma_no_cache_directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided {0} is invalid..
        /// </summary>
        internal static string The_provided_IAsyncResult_is_invalid {
            get {
                return ResourceManager.GetString("The_provided_IAsyncResult_is_invalid", resourceCulture);
            }
        }
    }
}
