//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.OutputCache.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.OutputCache.Resource.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get snapshot if not buffered..
        /// </summary>
        internal static string Cannot_get_snapshot_if_not_buffered {
            get {
                return ResourceManager.GetString("Cannot_get_snapshot_if_not_buffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use snapshot after headers sent..
        /// </summary>
        internal static string Cannot_use_snapshot_after_headers_sent {
            get {
                return ResourceManager.GetString("Cannot_use_snapshot_after_headers_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.AspNet.OutputCache Default In-Memory Provider.
        /// </summary>
        internal static string Microsoft_AspNet_OutputCache_Default_InMemory_Provider {
            get {
                return ResourceManager.GetString("Microsoft_AspNet_OutputCache_Default_InMemory_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UniqueId Cache Dependency.
        /// </summary>
        internal static string No_UniqueId_Cache_Dependency {
            get {
                return ResourceManager.GetString("No_UniqueId_Cache_Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider does not support policy for responses..
        /// </summary>
        internal static string Provider_does_not_support_policy_for_responses {
            get {
                return ResourceManager.GetString("Provider_does_not_support_policy_for_responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided {0} is invalid..
        /// </summary>
        internal static string The_provided_IAsyncResult_is_invalid {
            get {
                return ResourceManager.GetString("The_provided_IAsyncResult_is_invalid", resourceCulture);
            }
        }
    }
}
