//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.OutputCache.CosmosDBTableAsyncOutputCacheProvider.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.OutputCache.CosmosDBTableAsyncOutputCacheProvider.Resource.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the connection string by connection string name &apos;{0}&apos;..
        /// </summary>
        internal static string Cant_find_connectionString {
            get {
                return ResourceManager.GetString("Cant_find_connectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string name can&apos;t be empty..
        /// </summary>
        internal static string Cant_find_connectionStringName {
            get {
                return ResourceManager.GetString("Cant_find_connectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create table..
        /// </summary>
        internal static string Fail_to_create_table {
            get {
                return ResourceManager.GetString("Fail_to_create_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid storage account information provided. Please confirm the AccountName and AccountKey are valid in the web.config file - then restart the application..
        /// </summary>
        internal static string Invalid_storage_account_information {
            get {
                return ResourceManager.GetString("Invalid_storage_account_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name can&apos;t be empty..
        /// </summary>
        internal static string TableName_cant_be_empty {
            get {
                return ResourceManager.GetString("TableName_cant_be_empty", resourceCulture);
            }
        }
    }
}
